#!/bin/bash

mkdir tmp_generrors
awk '{print $2}' ./funs_tmp.txt | parallel './get_generror_from_abi_samples {} > ./tmp_generrors/{}'
awk '{print $2}' ./funs_tmp.txt | xargs -I % sh -c 'echo % $(cat ./tmp_generrors/%) >> generrors'

